### ISSUE TITLE
Disables secure DNS

### ISSUE THREAD

**Issue by hyprrt** [MulesGaming/brave-debullshitinator#2]
Doing any modifications to Brave disables secure DNS and you cannot turn it back on.

**Comment by MulesGaming** [comment]
This is a result of defualt Chromium behavior and I have opened a [report](https://issues.chromium.org/issues/384553529) to try and get it changed by if were being honest that's probably never going to happen. I have however forced secure DNS to "automatic" mode. This will enable secure DNS but falling back to normal DNS if that fails. I have updated the [customization guide](https://github.com/MulesGaming/brave-debullshitinator/wiki/Customization#secure-dns) on more info about changing secure dns's mode.

**Comment by hyprrt** [comment]
> This is a result of defualt Chromium behavior and I have opened a [report](https://issues.chromium.org/issues/384553529) to try and get it changed by if were being honest that's probably never going to happen. I have however forced secure DNS to "automatic" mode. This will enable secure DNS but falling back to normal DNS if that fails. I have updated the [customization guide](https://github.com/MulesGaming/brave-debullshitinator/wiki/Customization#secure-dns) on more info about changing secure dns's mode.

Is there no way to use a custom one such as Cloudflare or Google?

**Comment by MulesGaming** [comment]
Unfortunately it doesn't look like it.

**Comment by hyprrt** [comment]
> Unfortunately it doesn't look like it.

Alright. Thanks.

**Comment by MulesGaming** [comment]
There was a update on my big report that said:

> This is WAI because we want to disable DoH by default for managed devices and only want admins to be able to enable it (with the thinking that enterprise environments are the most prone to breakage through losing network-level visibility into DNS activity). I can update the policy text to mention this behavior.

https://issues.chromium.org/issues/384553529
